import 'package:flutter/material.dart';

void main() {
  runApp(const MyCalculatorUI());
}
class MyCalculatorUI extends StatelessWidget {
  const MyCalculatorUI({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyCalculator());
  }
}
class MyCalculator extends StatelessWidget {
  const MyCalculator({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("CALCULATOR"),
          centerTitle: true,
        backgroundColor: Colors.black54,
      ),
      body: Column(
        children:[
          Container(height: MediaQuery.of(context).size.height *0.3,
            color: Colors.black12,),
          Container(height: (MediaQuery.of(context).size.height *0.7)-80,
    color: Colors.black54,
          child: GridView.count(
          crossAxisCount: 4,
            children: [
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4, ) ,borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.teal, ),
              height: 100,
                width: 100,
                child: const Center(child: Text ("C",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),

              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.blueGrey, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("+/-",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.blueGrey, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("%",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.orangeAccent, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("÷",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),

              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("7",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("8",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("9",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.orangeAccent, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("x",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("4",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("5",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("6",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.orangeAccent, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("-",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("1",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("2",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("3",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.4,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.orangeAccent, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("+",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.3,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("0",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.2,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("00",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.2,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.black54, ),
                height: 100,
                width: 100,
                child: const Center(child: Text (".",style: TextStyle(fontSize: 50,color: Colors.white,fontWeight: FontWeight.bold),
                ),
                ),
              ),
              Container(decoration:  BoxDecoration(border: Border.all(color: Colors.grey,width: 0.2,),borderRadius: BorderRadius.all(Radius.circular(10)) ,color: Colors.orangeAccent, ),
                height: 100,
                width: 100,
                child: const Center(child: Text ("=",style: TextStyle(fontSize: 50,color: Colors.white),
                ),
                ),
              ),
            ],
          ),
          ),
        ]
      ),
    );
  }
}
